"""Initial migration

Revision ID: 082ca85d28f7
Revises: 
Create Date: 2026-04-10 13:26:52.144200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '082ca85d28f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_code', sa.String(length=10), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'ON_PATIENT', 'IN_TRANSIT', 'RETURNED', 'PROCESSING', 'MAINTENANCE', 'LOST', name='devicestatus'), nullable=True),
    sa.Column('chain_type', sa.Enum('WORKHORSE', 'POSTAL_72H', 'PURE_POSTAL', name='chaintype'), nullable=True),
    sa.Column('chain_position', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('last_maintenance_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personnummer', sa.String(length=13), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('webdoc_patient_id', sa.String(length=50), nullable=True),
    sa.Column('is_postal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_personnummer'), 'patients', ['personnummer'], unique=True)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('exam_type', sa.Enum('H24', 'H48', 'H72', name='examtype'), nullable=True),
    sa.Column('atgardskod', sa.String(length=10), nullable=True),
    sa.Column('price_sek', sa.Integer(), nullable=True),
    sa.Column('return_type', sa.Enum('CLINIC', 'POSTAL', name='returntype'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='examstatus'), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expected_removal_at', sa.DateTime(), nullable=True),
    sa.Column('actual_removal_at', sa.DateTime(), nullable=True),
    sa.Column('expected_return_at', sa.DateTime(), nullable=True),
    sa.Column('actual_return_at', sa.DateTime(), nullable=True),
    sa.Column('webdoc_booking_id', sa.String(length=50), nullable=True),
    sa.Column('webdoc_remiss_id', sa.String(length=50), nullable=True),
    sa.Column('remissvar_sent', sa.Boolean(), nullable=True),
    sa.Column('referring_physician', sa.String(length=100), nullable=True),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_events')
    op.drop_table('exams')
    op.drop_index(op.f('ix_patients_personnummer'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
